# Generated by Django 5.1.1 on 2024-10-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='footwear',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
    ]
